# Generated by Django 5.0.6 on 2024-06-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('word_language', models.CharField(blank=True, db_column='word_language', max_length=30, null=True)),
                ('translation_language', models.CharField(blank=True, db_column='translation_language', max_length=30, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, db_column='word', max_length=255, null=True)),
                ('translation', models.CharField(blank=True, db_column='translation', max_length=255, null=True)),
                ('is_learned', models.BooleanField(blank=True, db_column='is_learned', null=True)),
            ],
            options={
                'db_table': 'word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
